---
# roles/scaffold/tasks/scaffold-inventory.yml
# given a project from the projects dictionary

- name: assert '{{ scaffold_step }}' input for project '{{ project.name }}'
  assert:
    that:
      - targetdir is defined

- name: create '{{ project.inventory }}' inventory directory tree for project '{{ project.name}}'
  file:
    path: '{{ targetdir }}/{{item.path}}'
    state: directory
  with_filetree: '{{ role_path }}/templates/inventory/{{ project.inventory }}/'
  when: item.state == 'directory'

- name: create '{{ project.inventory }}' inventory templates for project '{{ project.name}}'
  template:
    src: '{{ item.src }}'
    dest: '{{ targetdir }}/{{item.path}}'
  with_filetree: '{{ role_path }}/templates/inventory/{{ project.inventory }}/'
  when: item.state == 'file'
